version: "3.8"

services:
  redis:
    image: redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - uploader
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  uploader:
    driver: bridge
